### PR TITLE
Integration specs and fix n+1 issue

### PR DESCRIPTION
**Pull request by fed1k**
* Make sure that the N+1 problem is solved when fetching all posts and their comments for a user. This is the corresponding wireframe
## Integration specs
* Use Capybara to write integration tests for each view in your project.
* User index page:

  * I can see the username of all other users.
  * I can see the profile picture for each user.
  * I can see the number of posts each user has written. 
  * When I click on a user, I am redirected to that user's show page.
* user show page:

  * I can see the user's profile picture.
  * I can see the user's username.
  * I can see the number of posts the user has written.
  * I can see the user's bio.
  * I can see the user's first 3 posts.
  * I can see a button that lets me view all of a user's posts.
  * When I click a user's post, it redirects me to that post's show page.
  * When I click to see all posts, it redirects me to the user's post's index page.
* User post index page:

  * I can see the user's profile picture.
  * I can see the user's username.
  * I can see the number of posts the user has written.
  * I can see a post's title.
  * I can see some of the post's body.
  * I can see the first comments on a post.
  * I can see how many comments a post has.
  * I can see how many likes a post has.
  * I can see a section for pagination if there are more posts than fit on the view.
  * When I click on a post, it redirects me to that post's show page.
* Post show page:

  * I can see the post's title.
  * I can see who wrote the post.
  * I can see how many comments it has.
  * I can see how many likes it has.
  * I can see the post body.
  * I can see the username of each commentor. 
  * I can see the comment each commentor left.

# Happy Reviewing🐱‍👤

### CODE REVIEW

**Review by smunozmo — CHANGES_REQUESTED** [review]
Hi @fed1k, 👋  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request ❌ 

- You have submitted a Pull Request that is not passing the linters tests, but don't worry, just work on that and submit your PR again when all three tests are green.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

⚠️  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by fed1k** [comment]
Hello Dear Code Reviewer. I do not know why these linter errors are showing on Github. They are not showing on my local machine

**Comment by smunozmo** [comment]
Hi @fed1k 👋 

For the Stylelint error just add an empty line at the end of that file, but for the Rubocop one I see that is a bug that happens depending on the OS, as this is your only problem you could add this in your .rubocop.yml file:

```
Layout/EndOfLine:
   Enabled: False
```

Happy coding! 🤓

**Review by zainsadaqat — CHANGES_REQUESTED** [review]
# Required Changes 🔁
# Hello  @fed1k 😄 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

- [ ] Please use @posts = @user.posts.includes(:comments) instead of @posts = @user.posts for posts#index.

_Check the comments under the review._




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by zainsadaqat — APPROVED** [review]
# APPROVED!!!! 🎉 🎉 🎉 🎉 🎉 🎉
## Hey @fed1k  😊 😃 

#### Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
